version: '3'
services:
    postgres:
      image: postgres:14.5
      restart: always
      environment:
        POSTGRES_USER: example
        POSTGRES_PASSWORD: example
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 1s
        timeout: 5s
        retries: 10
      ports:
        - 5432:5432
  
    prometheus:
        container_name: prometheus
        image: prom/prometheus:v2.48.1
        extra_hosts: ['host.docker.internal:host-gateway']
        command:
            - --enable-feature=exemplar-storage
            - --web.enable-remote-write-receiver
            - --config.file=/etc/prometheus/prometheus.yml
        volumes:
            - prometheus:/prometheus
            - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - 9090:9090
    grafana:
        container_name: grafana
        image: grafana/grafana
        extra_hosts: ['host.docker.internal:host-gateway']
        environment:
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
            - GF_AUTH_DISABLE_LOGIN_FORM=true
        volumes:
            - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
            - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
            - ./docker/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
            - ./docker/grafana/provisioning/alerting:/etc/grafana/provisioning/alerting:ro
        ports:
            - 3000:3000
    tempo:
        container_name: tempo
        image: grafana/tempo
        extra_hosts: ['host.docker.internal:host-gateway']
        command: ['-config.file=/etc/tempo.yml']
        volumes:
            - tempo:/tmp/tempo
            - ./docker/grafana/tempo.yml:/etc/tempo.yml:ro
        ports:
            - 3200:3200    # tempo
            - 9411:9411    # zipkin
    loki:
        container_name: loki
        image: grafana/loki
        extra_hosts: ['host.docker.internal:host-gateway']
        command: ['-config.file=/etc/loki/local-config.yaml']
        ports:
            - 3100:3100
volumes:
  prometheus:
    driver: local
  tempo:
    driver: local