spring:
  profiles.default: local
  application:
    name: transfer
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/example
    username: example
    password: example
  jpa:
    hibernate:
      ddl-auto: <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
management:
  server:
    port: 8081
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, prometheus
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
  tracing.sampling.probability: 1.0
  observations:
    key-values:
      application: transfer
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

# traceID and spanId are predefined MDC keys - we want the logs to include them
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
