spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/example
    username: example
    password: example
  jpa:
    hibernate:
      ddl-auto: <create | create-drop | update | validate | none>
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
