global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]
  - job_name: "transfer-service"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 2s
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8081"]
  - job_name: "tempo"
    static_configs:
      - targets: ["host.docker.internal:3200"]
